"""GitHub integration commands: `github-comment` and `badge`.

Both commands are intentionally stdlib-only (no httpx) so the action can run
in a minimal Python environment without extra dependencies.

`github-comment` builds a Markdown summary from a `mcptest run --json` payload
and POSTs it to the pull request via the GitHub REST API. Environment:

    GITHUB_TOKEN       — bearer token for api.github.com
    GITHUB_REPOSITORY  — "owner/repo"
    GITHUB_EVENT_PATH  — path to the webhook payload (parsed for PR number)

`badge` writes a shields.io-compatible endpoint JSON based on the same run
JSON, suitable for `https://img.shields.io/endpoint?url=...`.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any
from urllib import request as _urllib_request
from urllib.error import HTTPError, URLError

import click


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------


def _load_payload(input_path: str | None) -> dict[str, Any]:
    if input_path and input_path != "-":
        data = Path(input_path).read_text(encoding="utf-8")
    else:
        data = sys.stdin.read()
    if not data.strip():
        raise click.ClickException("expected JSON on stdin or via --input")
    try:
        return json.loads(data)
    except json.JSONDecodeError as exc:
        raise click.ClickException(f"invalid JSON: {exc}") from exc


def format_comment(payload: dict[str, Any]) -> str:
    """Build a Markdown PR comment from `mcptest run --json` output.

    Optionally includes:
    - A **Metrics** section when ``metric_summary`` is present in the payload.
    - A **Metric Regressions** section when a ``comparison`` key (from
      ``mcptest compare --json``) is present and contains regressions.
    """
    passed = payload.get("passed", 0)
    failed = payload.get("failed", 0)
    total = payload.get("total", passed + failed)
    emoji = "✅" if failed == 0 else "❌"

    lines = [
        f"{emoji} **mcptest**: {passed} passed, {failed} failed ({total} total)",
        "",
    ]

    failing = [c for c in payload.get("cases", []) if not c.get("passed", False)]
    if failing:
        lines.append("### Failures")
        for case in failing:
            suite = case.get("suite", "?")
            name = case.get("case", "?")
            err = case.get("error")
            lines.append(f"- **{suite}::{name}**")
            if err:
                lines.append(f"  - error: {err}")
            for a in case.get("assertions", []):
                if not a.get("passed", False):
                    lines.append(f"  - ✗ {a.get('name')}: {a.get('message')}")
        lines.append("")

    # Metrics summary section.
    metric_summary: dict[str, float] = payload.get("metric_summary", {})
    if metric_summary:
        lines.append("### Metrics")
        for name in sorted(metric_summary):
            score = metric_summary[name]
            indicator = "🟢" if score >= 0.8 else "🟡" if score >= 0.5 else "🔴"
            lines.append(f"- {indicator} **{name}**: {score:.3f}")
        lines.append("")

    # Metric regression section (populated when compare --json output is merged in).
    comparison: dict[str, Any] = payload.get("comparison", {})
    if comparison:
        regressions = [
            d for d in comparison.get("deltas", []) if d.get("regressed", False)
        ]
        if regressions:
            lines.append("### Metric Regressions")
            for r in regressions:
                name = r.get("name", "?")
                b = r.get("base_score", 0.0)
                h = r.get("head_score", 0.0)
                diff = r.get("delta", h - b)
                lines.append(
                    f"- ⚠️ **{name}**: {b:.3f} → {h:.3f} ({diff:+.3f})"
                )
            lines.append("")

    lines.append("<sub>Generated by <a href='https://github.com/josephgec/mcptest'>mcptest</a>.</sub>")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# github-comment
# ---------------------------------------------------------------------------


def _resolve_pr_number(event_path: str | None) -> int | None:
    if not event_path:
        return None
    p = Path(event_path)
    if not p.exists():
        return None
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None
    # Pull request events have `pull_request.number`; issue_comment events
    # have `issue.number` (and `issue.pull_request` present).
    if "pull_request" in data and isinstance(data["pull_request"], dict):
        return int(data["pull_request"].get("number", 0)) or None
    if "issue" in data and isinstance(data["issue"], dict):
        return int(data["issue"].get("number", 0)) or None
    if "number" in data:
        return int(data.get("number", 0)) or None
    return None


def post_comment(
    repo: str,
    pr_number: int,
    body: str,
    token: str,
    *,
    opener: Any = None,
) -> int:
    """POST a PR comment. Returns the HTTP status code.

    `opener` is injectable so tests can drive this without real network.
    Resolved at call time (not at function-definition time) so tests can
    monkeypatch `urllib.request.urlopen` via the module attribute.
    """
    if opener is None:
        opener = _urllib_request.urlopen
    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
    payload = json.dumps({"body": body}).encode("utf-8")
    req = _urllib_request.Request(
        url,
        data=payload,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "Content-Type": "application/json",
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": "mcptest-action",
        },
        method="POST",
    )
    try:
        response = opener(req)
    except HTTPError as exc:
        return exc.code
    except URLError as exc:  # pragma: no cover - network flake
        raise click.ClickException(f"failed to POST comment: {exc}")
    status = getattr(response, "status", None) or response.getcode()
    return int(status)


@click.command(
    help=(
        "Post a PR comment from mcptest JSON output. "
        "Reads GITHUB_TOKEN, GITHUB_REPOSITORY, and GITHUB_EVENT_PATH from env."
    )
)
@click.option(
    "--input",
    "input_path",
    default="-",
    type=click.Path(dir_okay=False),
    help="Path to `mcptest run --json` output. Use '-' (default) for stdin.",
)
@click.option(
    "--from-env",
    is_flag=True,
    help="Read token / repo / PR from the standard GitHub Actions env.",
)
@click.option("--repo", default=None, help="Override GITHUB_REPOSITORY.")
@click.option("--pr", "pr_number", type=int, default=None, help="Override PR number.")
@click.option("--token", default=None, help="Override GITHUB_TOKEN.")
@click.option(
    "--dry-run",
    is_flag=True,
    help="Print the comment body to stdout instead of posting.",
)
def github_comment_command(
    input_path: str,
    from_env: bool,
    repo: str | None,
    pr_number: int | None,
    token: str | None,
    dry_run: bool,
) -> None:
    payload = _load_payload(input_path)
    body = format_comment(payload)

    if dry_run:
        click.echo(body)
        return

    resolved_repo = repo or os.environ.get("GITHUB_REPOSITORY")
    resolved_token = token or os.environ.get("GITHUB_TOKEN")
    resolved_pr = pr_number
    if resolved_pr is None:
        resolved_pr = _resolve_pr_number(os.environ.get("GITHUB_EVENT_PATH"))

    if not resolved_repo or not resolved_token or not resolved_pr:
        raise click.ClickException(
            "missing GitHub context — need --repo/--pr/--token or GITHUB_REPOSITORY "
            "+ GITHUB_TOKEN + GITHUB_EVENT_PATH from the runner"
        )

    status = post_comment(
        resolved_repo, int(resolved_pr), body, resolved_token
    )
    if 200 <= status < 300:
        click.echo(f"posted comment (HTTP {status})")
    else:
        raise click.ClickException(
            f"GitHub API returned HTTP {status} when posting comment"
        )


# ---------------------------------------------------------------------------
# badge
# ---------------------------------------------------------------------------


def build_badge(payload: dict[str, Any]) -> dict[str, Any]:
    """Build a shields.io endpoint badge payload."""
    passed = payload.get("passed", 0)
    failed = payload.get("failed", 0)
    total = payload.get("total", passed + failed)
    color = "brightgreen" if failed == 0 and total > 0 else (
        "red" if failed > 0 else "lightgrey"
    )
    message = (
        "no tests"
        if total == 0
        else f"{passed}/{total} passing"
        if failed > 0
        else f"{total} passing"
    )
    return {
        "schemaVersion": 1,
        "label": "mcptest",
        "message": message,
        "color": color,
    }


@click.command(help="Emit a shields.io endpoint badge from mcptest JSON output.")
@click.option(
    "--input",
    "input_path",
    default="-",
    type=click.Path(dir_okay=False),
    help="Path to `mcptest run --json` output. Use '-' (default) for stdin.",
)
@click.option(
    "--output",
    "output_path",
    default=None,
    type=click.Path(dir_okay=False),
    help="Where to write the badge JSON (default: stdout).",
)
def badge_command(input_path: str, output_path: str | None) -> None:
    payload = _load_payload(input_path)
    badge = build_badge(payload)
    text = json.dumps(badge, indent=2)
    if output_path:
        Path(output_path).write_text(text + "\n", encoding="utf-8")
    else:
        click.echo(text)
